inherit_from: .rubocop_todo.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.5

# Check this as the value is changed somewhere after initial assignment.
Style/MutableConstant:
  Exclude:
    - 'lib/sitediff/sanitize/dom_transform.rb'
