inherit_from: .rubocop_todo.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.3

Naming/MethodName:
  EnforcedStyle: snake_case
  Exclude:
    # Overriding WEBrick::HTTPServlet::AbstractServlet::do_GET.
    # It's not ours to fix, it comes from the WEBrick libraries.
    - lib/sitediff/webserver/resultserver.rb

# Check this as the value is changed somewhere after initial assignment.
Style/MutableConstant:
  Exclude:
    - 'lib/sitediff/sanitize/dom_transform.rb'

# Disable rules enforcing unreadable programming styles
Style/ConditionalAssignment:
  Enabled: false
  
Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
