inherit_from: .rubocop_todo.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.3

Naming/MethodName:
  EnforcedStyle: snake_case
  Exclude:
    # Overriding WEBrick::HTTPServlet::AbstractServlet::do_GET.
    # It's not ours to fix, it comes from the WEBrick libraries.
    - lib/sitediff/webserver/resultserver.rb

# Check this as the value is changed somewhere after initial assignment.
Style/MutableConstant:
  Exclude:
    - 'lib/sitediff/sanitize/dom_transform.rb'

# Disable rules enforcing unreadable programming styles.
# Example: Use the return of the conditional for variable assignment
#   and comparison
Style/ConditionalAssignment:
  Enabled: false
  
Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# Classes can have as many lines as they want.
# Complex classes can have many methods after all.
Metrics/ClassLength:
  Enabled: false

# Methods can have a maximum of 128 lines.
# Complex methods might need to be broken in to multiple methods.
Metrics/MethodLength:
  Max: 64
  CountComments: false

# Methods can have a maximum of 128 lines.
# Complex methods might need to be broken in to multiple methods.
Metrics/BlockLength:
  CountComments: false
  Max: 64
