inherit_from: .rubocop_todo.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.3

Naming/MethodName:
  EnforcedStyle: snake_case
  Exclude:
    # Overriding WEBrick::HTTPServlet::AbstractServlet::do_GET.
    # It's not ours to fix, it comes from the WEBrick libraries.
    - lib/sitediff/webserver/resultserver.rb

# Check this as the value is changed somewhere after initial assignment.
Style/MutableConstant:
  Exclude:
    - 'lib/sitediff/sanitize/dom_transform.rb'

# Disable rules enforcing unreadable programming styles.
# Example: Use the return of the conditional for variable assignment
#   and comparison
Style/ConditionalAssignment:
  Enabled: false

# Require documentation for class methods.
Style/DocumentationMethod:
  Enabled: true

# Allow developers to write complex code.
Metrics/AbcSize:
  Max: 80

# Allow developers to write complex code.
Metrics/CyclomaticComplexity:
  Max: 15

# Allow developers to write complex code.
Metrics/PerceivedComplexity:
  Max: 15

# Classes can have as many lines as they want.
# Complex classes can have many methods after all.
Metrics/ClassLength:
  Enabled: false

# Methods can have a maximum of 128 lines.
# Complex methods might need to be broken in to multiple methods.
Metrics/MethodLength:
  Max: 64
  CountComments: false

# Methods can have a maximum of 128 lines.
# Complex methods might need to be broken in to multiple methods.
Metrics/BlockLength:
  CountComments: false
  Max: 64

# Some files have very long lines and need to be ignored.
# Otherwise, we enforce a max-length of 80 characters per line.
Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  IgnoredPatterns:
    - '^\s*SiteDiff\.log'
    - '^\s*run\s'
    - '\sif|elsif|unless\s'
  Exclude:
    - 'Thorfile'
    # Spec files contain long strings for testing, so we ignore them.
    - 'spec/**/*_spec.rb'

# MarshalLoad helps in creating a clone of a Ruby hash, ensuring that it is
# completely disconnected from the original hash. A common way of doing this
# is by serializing an object and then un-serializing it with Marshal.
Security/MarshalLoad:
  Exclude:
    - 'lib/sitediff/cache.rb'
