# Offense count: 3
Lint/IneffectiveAccessModifier:
  Exclude:
    - 'lib/sitediff/config.rb'

# Offense count: 1
Lint/NestedMethodDefinition:
  Exclude:
    - 'lib/sitediff/config/creator.rb'

# Offense count: 2
# Configuration parameters: ContextCreatingMethods, MethodCreatingMethods.
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/sitediff/config.rb'
    - 'lib/sitediff/webserver.rb'

# Offense count: 14
Metrics/AbcSize:
  Max: 61

# Offense count: 6
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 52

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 171

# Offense count: 5
Metrics/CyclomaticComplexity:
  Max: 11

# Offense count: 19
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 33

# Offense count: 3
Metrics/PerceivedComplexity:
  Max: 11

# Offense count: 1
Naming/BinaryOperatorParameterName:
  Exclude:
    - 'lib/sitediff/uriwrapper.rb'

# Offense count: 1
Naming/ConstantName:
  Exclude:
    - 'lib/sitediff/sanitize/dom_transform.rb'

# Offense count: 1
Security/MarshalLoad:
  Exclude:
    - 'lib/sitediff/cache.rb'

# Offense count: 1
Security/Open:
  Exclude:
    - 'spec/fixtures/fixture_spec.rb'

# Offense count: 21
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'Thorfile'
    - 'lib/sitediff.rb'
    - 'lib/sitediff/cache.rb'
    - 'lib/sitediff/cli.rb'
    - 'lib/sitediff/config.rb'
    - 'lib/sitediff/config/creator.rb'
    - 'lib/sitediff/crawler.rb'
    - 'lib/sitediff/diff.rb'
    - 'lib/sitediff/fetch.rb'
    - 'lib/sitediff/result.rb'
    - 'lib/sitediff/sanitize.rb'
    - 'lib/sitediff/sanitize/regexp.rb'
    - 'lib/sitediff/uriwrapper.rb'
    - 'lib/sitediff/webserver.rb'
    - 'lib/sitediff/webserver/resultserver.rb'

# Offense count: 1
# Configuration parameters: .
# SupportedStyles: annotated, template, unannotated
Style/FormatStringToken:
  EnforcedStyle: unannotated

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/sitediff/uriwrapper.rb'
    - 'lib/sitediff/webserver.rb'

# Offense count: 1
Style/MultilineTernaryOperator:
  Exclude:
    - 'lib/sitediff/diff.rb'

# Offense count: 1
Style/StructInheritance:
  Exclude:
    - 'lib/sitediff/result.rb'

# Offense count: 19
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 178
